### ISSUE TITLE
Panic with CGI scripts called via HTTP/3

### ISSUE THREAD

**Issue by jum** [aksdb/caddy-cgi#19]
Whenever a CGI script is called from client that uses HTTP/3 aka QUIC the following panic appears in my log:

```
Oct 18 15:20:10 hostname.dom.ain caddy[27043]: {"level":"info","ts":1729257610.4583259,"msg":"ERROR http: panic serving arg=\"interface conversion: *encode.responseWriter is not http.Flusher: missing method Flush\" trace=\"goroutine 609 [running]:
github.com/quic-go/quic-go/http3.(*Server).handleRequest.func2.1()
	github.com/quic-go/quic-go@v0.48.0/http3/server.go:682 +0xb9
panic({0x1a45d40?, 0xc00025def0?})
	runtime/panic.go:785 +0x132
github.com/aksdb/caddy-cgi/v2.instantWriter.Write({{0x21bc530?, 0xc0008a4460?}}, {0xc00003bc77?, 0x400?, 0x0?})
	github.com/aksdb/caddy-cgi/v2@v2.2.3/cgi.go:185 +0x94
bufio.(*Reader).writeBuf(0xc000b79680, {0x7fc8e48bc100?, 0xc000c14400?})
	bufio/bufio.go:560 +0x5e
bufio.(*Reader).WriteTo(0xc000b79680, {0x7fc8e48bc100, 0xc000c14400})
	bufio/bufio.go:518 +0x36
io.copyBuffer({0x7fc8e48bc100, 0xc000c14400}, {0x21aa500, 0xc000b79680}, {0x0, 0x0, 0x0})
	io/io.go:411 +0x9d
io.Copy(...)
	io/io.go:388
net/http/cgi.(*Handler).ServeHTTP(0xc000ae7b68, {0x21bb448, 0xc000c14400}, 0xc000d5be00)
	net/http/cgi/host.go:342 +0x1e25
github.com/aksdb/caddy-cgi/v2.(*CGI).ServeHTTP(0xc000818d20, {0x21bc530, 0xc0008a4460}, 0xc000d5be00, {0xc000ae7d68?, 0x410d45?})
	github.com/aksdb/caddy-cgi/v2@v2.2.3/cgi.go:169 +0xe3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21acb20?, {0x21bc530?, 0xc0008a4460?}, 0xc000d5be00?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:303 +0x325
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005a1508?, {0x21bc530?, 0xc0008a4460?}, 0x21acb20?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc00020ca20, {0x21bc530, 0xc0008a4460}, 0xc000d5be00, {0x21acb20, 0xc00009e860})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/subroute.go:74 +0x67
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21acb20?, {0x21bc530?, 0xc0008a4460?}, 0x7?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:303 +0x325
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc530?, 0xc0008a4460?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc530, 0xc0008a4460}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00025daa0?, {0x21bc530?, 0xc0008a4460?}, 0x4?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp/encode.(*Encode).ServeHTTP(0xc000209480, {0x21bc650, 0xc00025de00}, 0xc000d5be00, {0x21acb20, 0xc00009e900})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/encode/encode.go:179 +0x542
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x21bc650, 0xc00025de00}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21acb20?, {0x21bc650?, 0xc00025de00?}, 0xc000d5be00?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc650, 0xc00025de00}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:303 +0x325
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x21bc650?, 0xc00025de00?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x21bc650, 0xc00025de00}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00025dce0?, {0x21bc650?, 0xc00025de00?}, 0x0?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp/headers.Handler.ServeHTTP({0x0?, 0xc000230a98?}, {0x7fc8e4962858, 0xc000208700}, 0xc000d5be00, {0x21acb20, 0xc00009e940})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/headers/headers.go:110 +0x2bf
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000612ed8?, {0x7fc8e4962858?, 0xc000208700?}, 0x4?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.VarsMiddleware.ServeHTTP(0xc0007a8f00, {0x7fc8e4962858, 0xc000208700}, 0xc000d5be00, {0x21acb20, 0xc00025dda0})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/vars.go:71 +0x2c2
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21acb20?, {0x7fc8e4962858?, 0xc000208700?}, 0xc000d5be00?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:303 +0x325
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005a0a88?, {0x7fc8e4962858?, 0xc000208700?}, 0x21acb20?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc00020c3a0, {0x7fc8e4962858, 0xc000208700}, 0xc000d5be00, {0x21acb20, 0x1fa8758})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/subroute.go:74 +0x67
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:336 +0xd2
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21acb20?, {0x7fc8e4962858?, 0xc000208700?}, 0xc000d5be00?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:303 +0x325
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x7fc8e4962858?, 0xc000208700?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x7fc8e4962858?, 0xc000208700?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x7fc8e4962858?, 0xc000208700?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x7fc8e4962858?, 0xc000208700?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x21c0668?, {0x7fc8e4962858?, 0xc000208700?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Compile.wrapRoute.func1.1({0x7fc8e4962858, 0xc000208700}, 0xc000d5be00)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/routes.go:271 +0x244
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00025dd40?, {0x7fc8e4962858?, 0xc000208700?}, 0xc000c14100?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x7fc8e4962858?, 0xc000208700?}, 0xc000c14100?, {0x21acb20?, 0xc000364c40?})
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/server.go:480 +0x24b
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Provision.(*Server).wrapPrimaryRoute.func2({0x7fc8e4962858?, 0xc000208700?}, 0x4eae2f?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/server.go:456 +0x35
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0007f8d00?, {0x7fc8e4962858?, 0xc000208700?}, 0xc000d5be00?)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/caddyhttp.go:58 +0x29
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc000704008, {0x21bc1b0, 0xc000af9b80}, 0xc000d5bb80)
	github.com/caddyserver/caddy/v2@v2.9.0-beta.2.0.20241016012820-c6f2979986d8/modules/caddyhttp/server.go:368 +0xc88
github.com/quic-go/quic-go/http3.(*Server).handleRequest.func2(0x21c06a0?, 0xc0008a4320?, {0x21ad2e0?, 0xc000704008?}, 0xc0007cf220?, 0xa?)
	github.com/quic-go/quic-go@v0.48.0/http3/server.go:690 +0x5f
github.com/quic-go/quic-go/http3.(*Server).handleRequest(0xc0004ab2c0, 0xc00031f570, {0x21cf078, 0xc000b79380}, 0xc0008a4370, 0xc000b79140)
	github.com/quic-go/quic-go@v0.48.0/http3/server.go:691 +0xac5
github.com/quic-go/quic-go/http3.(*Server).handleConn.func1()
	github.com/quic-go/quic-go@v0.48.0/http3/server.go:578 +0x5b
created by github.com/quic-go/quic-go/http3.(*Server).handleConn in goroutine 589
	github.com/quic-go/quic-go@v0.48.0/http3/server.go:574 +0x32d
""}

```

**Comment by aksdb** [comment]
You'll have to disable "unbufferedOutput" then.
I'll see if there is a way with http3 as well, but I have no experience with it yet and no immediate idea how to test it.

**Comment by aksdb** [comment]
Hmm, the problem doesn't even directly seem to be HTTP3. Apparently it's more that caddy uses a wrapper for encoding the response. Something related to `AcceptEncoding` then. Maybe compression?
I guess I can only silently ignore the attempt to flush then.

**Comment by aksdb** [comment]
Give version 2.2.4 a shot, please.

**Comment by jum** [comment]
Thank you a lot! I have built my caddy with that version, and the old CGI scripts work fine.
